compressionLevel: mixed

enableGlobalCache: false

checksumBehavior: update

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.3.cjs

npmScopes:
  greenfinity:
    npmPublishRegistry: https://npm.greenfinity.hu/
